name: Unit Testing

on:
  push:
    branches:
      - test

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          make install  

      - name: Run unit tests
        run: |
          make test  
